### PR TITLE
fix LR tests

### PR DESCRIPTION
**Pull request by gurneyalex**
fix the tests depending on the PO generated from a Tender to be confirmed.
purchase-workflow/bb44c74e62 changed the behavior to generate a draftpo PO.

### CODE REVIEW

**Comment by gurneyalex** [comment]
I'd like a quick merge for this (as soon as travis is :green_heart: would be nice)

**Comment by lepistone** [comment]
thanks for fixing :+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by gurneyalex** [comment]
thx :heart_eyes_cat:

**Pull request merged**
