### PR TITLE
Add domain on location in LRS: must be of type internal

### PR DESCRIPTION
**Pull request by jgrandguillaume**
Hi,

We want a domain on internal location because it's a non-sense to look for "customer" location or "supplier" or "view". Dispatch is "by definition" from internal location.

Regards

### CODE REVIEW

**Comment by lepistone** [comment]
:+1: thanks

**Comment by gurneyalex** [comment]
I think the domain may be wrong ('!=' instead of '='). Can someone confirm?

**Comment by lepistone** [comment]
looks like you're right, well spotted @gurneyalex

**Comment by gurneyalex** [comment]
:-1: as is.

**Comment by lepistone** [comment]
I flipped the domain and :+1:

**Comment by gurneyalex** [comment]
:+1: thanks @lepistone

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
