### PR TITLE
Set all fields readonly for cancelled Logistics order

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by nbessi** [comment]
seems ok :+1:  but one job failed because pytz is missing so  maybe an :hand:

**Comment by lepistone** [comment]
:+1:

**Comment by yvaucher** [comment]
I just restarted travis failing job and it works.

**Comment by nbessi** [comment]
:+1:

**Comment by gurneyalex** [comment]
I really don't like doing things that way, as it only works at the web client level and the fields are not truely read only. 

OTOH, it seems to be the way things are done in the core (except that for some reason they tend to set readonly=True by default and relax the constraint for some states). 

So :+1: reluctantly

**Pull request merged**
