### PR TITLE
fix regression: soucing 'other' is always OK

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1: Thanks

**Comment by lepistone** [comment]
@yvaucher I made the same change on `framework_agreement_sourcing`.

**Comment by yvaucher** [comment]
@lepistone perfect thanks

**Comment by nbessi** [comment]
Without further info or a issue :hand:  even if code seems correct the meaning of the patch seems odd

**Comment by lepistone** [comment]
Hi @nbessi . You're right, I can explain a bit more.

What happened is that @yvaucher changed the behaviour of the sourcing of type "other", so that is passes all the time. This change is indeed correct.

At the same time, in my branch I was improving the check system for adding detailed feedback of what was wrong. To do that, I refactored the methods that perform the checks to return a list of error strings instead of a boolean. We didn't realise that we were touching the same thing, so my patch inadvertently reverted @yvaucher 's change.

This PR fixes that situation. Thanks

**Comment by nbessi** [comment]
:+1:

**Pull request merged**
