### PR TITLE
8.0 logistic order

### PR DESCRIPTION
**Pull request by yvaucher**
This is a takeover of #6 

It depends on #6 and OCA/sale-workflow#41

### CODE REVIEW

**Comment by lepistone** [comment]
All dependencies have now been merged: I will restart the build and review. Thanks!

**Comment by lepistone** [comment]
...and we're green! Can you add some information in the manifest about what this module does? The copyrights should probably say 2013-2014. Otherwise LGTM, thanks!

**Comment by gurneyalex** [comment]
:+1:

**Comment by yvaucher** [comment]
@lepistone improvements done in manifest. Thanks

**Comment by lepistone** [comment]
thanks :+1:

**Pull request merged**
