### PR TITLE
fix view of sale order that seems to break

### PR DESCRIPTION
**Pull request by lepistone**
@yvaucher do you agree with this? Thanks!

### CODE REVIEW

**Comment by yvaucher** [comment]
warehouse_id should be present in `sale_stock` which is a dependency of `logistic_consignee`

Does it create an error on install and/or update?

**Comment by lepistone** [comment]
@yvaucher on update.

Probably the situation is that if some view changes a field introduced in another view without explicit inheritance of views of dependency of modules, then the update could fail or not depending on the order the graph is transversed.

**Comment by yvaucher** [comment]
Ok warehouse_id added in sale_stock is the one on sale order level. Warehouse_id is not added in dependencies. then :+1:

**Comment by jgrandguillaume** [comment]
LGTM, tested. :+1:

**Pull request merged**
