### PR TITLE
add .gitignore & LICENSE

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
And the other files (LICENSE, README...)?

**Comment by yvaucher** [comment]
I think it can be done in multiple PR one thing at a time

**Comment by pedrobaeza** [comment]
I think those two (or at least LICENSE) are very straight-forward to deserve a unique PR...

**Comment by yvaucher** [comment]
travis should be done in another PR, it has some specificities to be done with addons-backport.
This branch should override official addons and some little hack will need to be done for that.

**Comment by pedrobaeza** [comment]
:+1: 

OK, let's do Travis stuff on other PR

**Comment by eLBati** [comment]
:+1:

**Pull request merged**
