### PR TITLE
8.0 Logistics Requisition and Logisitcs Budget UI improvements

### PR DESCRIPTION
**Pull request by yvaucher**
As changes in both modules are dependent, I do this in one PR to keep travis green

### CODE REVIEW

**Comment by yvaucher** [comment]
Included https://github.com/OCA/vertical-ngo/pull/28 to make travis green

**Comment by lepistone** [comment]
thanks :+1:

**Comment by gurneyalex** [comment]
@yvaucher could you rebase?

**Comment by lepistone** [comment]
@yvaucher FYI the conflict is in a view.

**Comment by gurneyalex** [comment]
with my fix, :+1:

**Pull request merged**
