### PR TITLE
[8.0] port module logistic_requistion_budget

### PR DESCRIPTION
**Pull request by yvaucher**
depends on:
- [x] https://github.com/OCA/vertical-ngo/pull/8

### CODE REVIEW

**Comment by gurneyalex** [comment]
Please rename to logistic_budget

**Comment by lepistone** [comment]
Code review :+1: 
Waiting for #8 to test that a bit. Thanks!

**Comment by max3903** [comment]
:+1:

**Comment by lepistone** [comment]
@yvaucher I agree with disabling the test, because of an external bug. Could please note somewhere very visible (like the manifest) about that, so that we do not forget to reactivate it if the bug is fixed? thanks!

**Pull request merged**
