### PR TITLE
adapt framework_agreement_sourcing to agreement 2.0

### PR DESCRIPTION
**Pull request by lepistone**
Depends on:
- [ ] OCA/purchase-workflow#101

### CODE REVIEW

**Comment by yvaucher** [comment]
```
 ParseError: "External ID not found in the system: framework_agreement.purchase_order_form" while parsing /home/travis/build/OCA/vertical-ngo/framework_agreement_requisition/view/purchase_order.xml
```

This error is due to dependency

**Comment by gurneyalex** [comment]
@lepistone I just made a small update on your branch:
1. typo fix
2. edit travis.yml to build with the not yet merged branch of purchase-workflow (will revert this bit before merging)

**Comment by gurneyalex** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
