### PR TITLE
compute tender picking type on creation from LR

### PR DESCRIPTION
**Pull request by lepistone**
The logic implemented in the onchange is correct. This uses it also when
a tender is created from a logistic requisition.

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
Sorry, only partially ok... Looks in the trello board

**Comment by lepistone** [comment]
OK, :triangular_flag_on_post: while I debug this.

**Comment by lepistone** [comment]
@jgrandguillaume I think this PR is correct, and I fixed the onchange address -> picking type in OCA/purchase-workflow#104, both for orders and requisitions.

**Comment by jgrandguillaume** [comment]
Ok, Thanks !

:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
