### PR TITLE
fix shipment from/dest locations for donations

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by lepistone** [comment]
I'm linting and improving the test.

**Comment by lepistone** [comment]
Wow, such fixup...

we might want to squash

**Comment by lepistone** [comment]
wow, more fixup to do. I'm taking care of that.

**Comment by gurneyalex** [comment]
squashed.

**Comment by yvaucher** [comment]
:+1:

**Comment by gurneyalex** [comment]
superseeded by #144

**Pull request closed without merging**
