### PR TITLE
Move transport_plan as stock_shipment_management in OCA/stock-logistics-workflow

### PR DESCRIPTION
**Pull request by yvaucher**
Moved in https://github.com/OCA/stock-logistics-workflow/pull/50

### CODE REVIEW

**Comment by lepistone** [comment]
:+1:

**Comment by gurneyalex** [comment]
can't merge this until OCA/stock-logistics-workflow#50 is green

**Comment by lepistone** [comment]
you're right @gurneyalex. I marked this one WIP as well, we'll merge them at the same time. Sorry for the noise.

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
