### PR TITLE
ui fix: align budget fields of LR line form

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by lepistone** [comment]
On the red travis:

It is on odoo only, on tests with `assertraises`. It is not related to this PR. I think I know what that is, I will address it separately. Please consider that build as green.

**Comment by lepistone** [comment]
The red build in with odoo is due to https://github.com/odoo/odoo/issues/3697. Still unrelated to this PR.

**Comment by yvaucher** [comment]
@lepistone not sure about this one. Doesn't it throw description below ?

**Comment by lepistone** [comment]
you're right @yvaucher. I'm fixing.

**Comment by lepistone** [comment]
@yvaucher should be OK now. I also switched the budget column to the right.

**Comment by lepistone** [comment]
@yvaucher I applied the same change in the lrl form inside the lr form

**Comment by yvaucher** [comment]
:+1:

**Comment by nbessi** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Pull request merged**
