### PR TITLE
8.0 Logistics Order - UI Improvement the return

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by lepistone** [comment]
:+1:

**Comment by yvaucher** [comment]
rebased and fixed 2nd commit message typo

**Comment by lepistone** [comment]
@gurneyalex can you please fast-track this one? I just realized it contains improvements on `logistic_budget`, and I should rebase #68 on top of this one.

Thanks!

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
