### PR TITLE
Move transport_information module in OCA/stock-logistics-workflow

### PR DESCRIPTION
**Pull request by yvaucher**
Moved in PR:
- [x] https://github.com/OCA/stock-logistics-workflow/pull/51

### CODE REVIEW

**Comment by lepistone** [comment]
thanks :+1:

**Comment by lepistone** [comment]
actually :triangular_flag_on_post: you should add pull stock-logistic-workflow in the .travis.yml

**Comment by yvaucher** [comment]
@lepistone Right thanks

Just fixed it. But it will still be red until #51 is merged.

**Comment by rdeheele** [comment]
:+1:

**Comment by lepistone** [comment]
We're good! thanks

**Pull request merged**
