### PR TITLE
Add Stock owner to propagate it to cost estimate lines

### PR DESCRIPTION
**Pull request by yvaucher**
Based on(includes other PR commits)  : 
- [x] https://github.com/OCA/vertical-ngo/pull/97

Depends on:
- [x] https://github.com/OCA/sale-workflow/pull/89

### CODE REVIEW

**Comment by lepistone** [comment]
Now that we merged #92 and #97 this probably needs a rebase.

**Comment by yvaucher** [comment]
Indeed, rebased

**Comment by lepistone** [comment]
This is now ready and green!

**Comment by yvaucher** [comment]
:+1: 

And thanks for the fix in donation module

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
